import type { Status, Account, Tag } from '../types';

export const mockAccount: Account = {
  id: '1',
  username: 'demo_user',
  acct: 'demo_user@mastodon.social',
  display_name: 'Demo User',
  locked: false,
  bot: false,
  created_at: '2023-01-01T00:00:00.000Z',
  note: 'This is a demo account for testing the Mastodon client.',
  url: 'https://mastodon.social/@demo_user',
  avatar: 'https://via.placeholder.com/150/2b90d9/ffffff?text=DU',
  avatar_static: 'https://via.placeholder.com/150/2b90d9/ffffff?text=DU',
  header: 'https://via.placeholder.com/1500x500/1f232b/ffffff?text=Header',
  header_static: 'https://via.placeholder.com/1500x500/1f232b/ffffff?text=Header',
  followers_count: 1234,
  following_count: 567,
  statuses_count: 8901,
  last_status_at: new Date().toISOString(),
  emojis: [],
  fields: [],
};

const createMockAccount = (id: string, username: string, displayName: string): Account => ({
  ...mockAccount,
  id,
  username,
  acct: `${username}@mastodon.social`,
  display_name: displayName,
  avatar: `https://via.placeholder.com/150/${Math.random() > 0.5 ? '2b90d9' : '6364ff'}/ffffff?text=${displayName.substring(0, 2)}`,
});

const sampleAccounts = [
  createMockAccount('2', 'alice', 'Alice Network'),
  createMockAccount('3', 'bob_dev', 'Bob Developer'),
  createMockAccount('4', 'charlie', 'Charlie Tech'),
  createMockAccount('5', 'dana_ops', 'Dana DevOps'),
];

export const mockStatuses: Status[] = [
  {
    id: '1',
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    in_reply_to_id: null,
    in_reply_to_account_id: null,
    sensitive: false,
    spoiler_text: '',
    visibility: 'public',
    language: 'en',
    uri: 'https://mastodon.social/@alice/1',
    url: 'https://mastodon.social/@alice/1',
    replies_count: 3,
    reblogs_count: 5,
    favourites_count: 12,
    favourited: false,
    reblogged: false,
    muted: false,
    bookmarked: false,
    content: '<p>Just finished setting up our new network infrastructure with <a href="#" class="mention hashtag">#networking</a> <a href="#" class="mention hashtag">#infrastructure</a>. The performance improvements are incredible!</p>',
    reblog: null,
    application: { name: 'Web', website: null },
    account: sampleAccounts[0],
    media_attachments: [],
    mentions: [],
    tags: [
      { name: 'networking', url: 'https://mastodon.social/tags/networking' },
      { name: 'infrastructure', url: 'https://mastodon.social/tags/infrastructure' },
    ],
    emojis: [],
    card: null,
    poll: null,
  },
  {
    id: '2',
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    in_reply_to_id: null,
    in_reply_to_account_id: null,
    sensitive: false,
    spoiler_text: '',
    visibility: 'public',
    language: 'en',
    uri: 'https://mastodon.social/@bob_dev/2',
    url: 'https://mastodon.social/@bob_dev/2',
    replies_count: 7,
    reblogs_count: 15,
    favourites_count: 28,
    favourited: true,
    reblogged: false,
    muted: false,
    bookmarked: true,
    content: '<p>Working on a new React component library with TypeScript. Type safety is a game changer! 🚀</p><p><a href="#" class="mention hashtag">#react</a> <a href="#" class="mention hashtag">#typescript</a> <a href="#" class="mention hashtag">#webdev</a></p>',
    reblog: null,
    application: { name: 'Web', website: null },
    account: sampleAccounts[1],
    media_attachments: [],
    mentions: [],
    tags: [
      { name: 'react', url: 'https://mastodon.social/tags/react' },
      { name: 'typescript', url: 'https://mastodon.social/tags/typescript' },
      { name: 'webdev', url: 'https://mastodon.social/tags/webdev' },
    ],
    emojis: [],
    card: null,
    poll: null,
  },
  {
    id: '3',
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    in_reply_to_id: null,
    in_reply_to_account_id: null,
    sensitive: false,
    spoiler_text: '',
    visibility: 'public',
    language: 'en',
    uri: 'https://mastodon.social/@charlie/3',
    url: 'https://mastodon.social/@charlie/3',
    replies_count: 2,
    reblogs_count: 8,
    favourites_count: 19,
    favourited: false,
    reblogged: true,
    muted: false,
    bookmarked: false,
    content: '<p>Interesting article on distributed systems and CAP theorem. Worth a read for anyone working with microservices!</p><p><a href="#" class="mention hashtag">#distributedsystems</a> <a href="#" class="mention hashtag">#microservices</a></p>',
    reblog: null,
    application: { name: 'Web', website: null },
    account: sampleAccounts[2],
    media_attachments: [],
    mentions: [],
    tags: [
      { name: 'distributedsystems', url: 'https://mastodon.social/tags/distributedsystems' },
      { name: 'microservices', url: 'https://mastodon.social/tags/microservices' },
    ],
    emojis: [],
    card: null,
    poll: null,
  },
  {
    id: '4',
    created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    in_reply_to_id: null,
    in_reply_to_account_id: null,
    sensitive: false,
    spoiler_text: '',
    visibility: 'public',
    language: 'en',
    uri: 'https://mastodon.social/@dana_ops/4',
    url: 'https://mastodon.social/@dana_ops/4',
    replies_count: 5,
    reblogs_count: 12,
    favourites_count: 25,
    favourited: false,
    reblogged: false,
    muted: false,
    bookmarked: false,
    content: '<p>Successfully migrated our entire infrastructure to Kubernetes. The deployment process is now so smooth!</p><p>Key takeaways:<br>- Automation is everything<br>- Monitoring from day one<br>- GitOps for the win</p><p><a href="#" class="mention hashtag">#kubernetes</a> <a href="#" class="mention hashtag">#devops</a> <a href="#" class="mention hashtag">#cloudnative</a></p>',
    reblog: null,
    application: { name: 'Web', website: null },
    account: sampleAccounts[3],
    media_attachments: [],
    mentions: [],
    tags: [
      { name: 'kubernetes', url: 'https://mastodon.social/tags/kubernetes' },
      { name: 'devops', url: 'https://mastodon.social/tags/devops' },
      { name: 'cloudnative', url: 'https://mastodon.social/tags/cloudnative' },
    ],
    emojis: [],
    card: null,
    poll: null,
  },
  {
    id: '5',
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    in_reply_to_id: null,
    in_reply_to_account_id: null,
    sensitive: false,
    spoiler_text: '',
    visibility: 'public',
    language: 'en',
    uri: 'https://mastodon.social/@alice/5',
    url: 'https://mastodon.social/@alice/5',
    replies_count: 1,
    reblogs_count: 3,
    favourites_count: 8,
    favourited: false,
    reblogged: false,
    muted: false,
    bookmarked: false,
    content: '<p>Morning coffee and debugging session. Found the issue in our routing configuration - a single typo cost us 2 hours! 😅</p><p><a href="#" class="mention hashtag">#networking</a> <a href="#" class="mention hashtag">#debugging</a></p>',
    reblog: null,
    application: { name: 'Web', website: null },
    account: sampleAccounts[0],
    media_attachments: [],
    mentions: [],
    tags: [
      { name: 'networking', url: 'https://mastodon.social/tags/networking' },
      { name: 'debugging', url: 'https://mastodon.social/tags/debugging' },
    ],
    emojis: [],
    card: null,
    poll: null,
  },
];

export const mockTrendingTags: Tag[] = [
  {
    name: 'networking',
    url: 'https://mastodon.social/tags/networking',
    history: [
      { day: new Date().toISOString(), uses: '245', accounts: '128' },
    ],
  },
  {
    name: 'kubernetes',
    url: 'https://mastodon.social/tags/kubernetes',
    history: [
      { day: new Date().toISOString(), uses: '189', accounts: '94' },
    ],
  },
  {
    name: 'webdev',
    url: 'https://mastodon.social/tags/webdev',
    history: [
      { day: new Date().toISOString(), uses: '312', accounts: '156' },
    ],
  },
  {
    name: 'devops',
    url: 'https://mastodon.social/tags/devops',
    history: [
      { day: new Date().toISOString(), uses: '167', accounts: '89' },
    ],
  },
  {
    name: 'typescript',
    url: 'https://mastodon.social/tags/typescript',
    history: [
      { day: new Date().toISOString(), uses: '134', accounts: '72' },
    ],
  },
];

export const mockFollowedTags: Tag[] = [
  { name: 'networking', url: 'https://mastodon.social/tags/networking' },
  { name: 'react', url: 'https://mastodon.social/tags/react' },
  { name: 'typescript', url: 'https://mastodon.social/tags/typescript' },
];
